name: Hugo est passe par la 
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./1.Docker/300123679
        with:
          MY_NAME: "hponnan"
