#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp and docker.
groups:
  - ubuntu: [root,sys]
  - hashicorp
  - docker

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCBdeNnWPDPlqycwxRKYX9L5vM5+9Ggb89skVYBGhDqvDO0kIRQ3BmAXnj54Djb3Kn3wmW6mb/cf9RFV6NOy0N0mem6y5XywZBI6amqz3lHWA4wCk8julPkEMygBs7NX+GbquMiY/J5SCf0fPHgdpxQ1ulFo6cTaOgaMor4Mw8M/yZWpgZW1v/0IlG1ZJKzclQD0vhJyPreqSG0GgZGb89n6pb1UkJdJReH5T5M0hlo8d1E1j4Y8AybtVHpFpwGcVYcnaEDeOVaWww5Mc+saIjUbKpJhbShpZNtGS8O4zw0c1iJR1seHbJjg5JI+0vl+cY5bVTN7B5XVIxEZ7248iQbC+85nMUmYfM/QhW5zGNr/SnPXxz7B92bZWyI/FOqmufrCumjQDwJx29AQdFzyBpZIrkZEh859livoooLJPZu595EQZ+Md4z+13kfkOKsTbZbqg8f3olwh77Aftkn/NuJuI0PjiXZ61xT0bub/IDc4ZfrcIeJjHv3A14G2I0uvk= sylva@LAPTOP-0TCDMERH
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD2pLhMqFGKffSdYvNCMAyM7598oBY+m/3q5AMXmb7IE6vq42+yGzqEUzZu9WrFckFD4Hq52rIU5DeOvi83DCF3uroXjNTEtCKdi+tY7cV18bHmsDsBHMqTnpuvroofgFWA0Pi++b2kGW2I5eyy1Qjv5rOp7y11Xe6XeZFEz7qQO1/xNiBMJEruG9Xldgooe4hkaOF39qnbqD4ui3LxYaTUTEulstw4wN70dSB8Zu9YQP7A7KU2zIEwJ1aw8whfO1CAM/AVvoDyqMtV8VXoaZSHOBgluMtinQfyyt473S2ZZeJlnmhK0F1gdOhO4SVZNRMj96m30ryYkYBFWvvLRP5N b300098957@ramena
      
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - net-tools
  - jq

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1