name: "Hello Actions"
description: "Greet someone"
author: "ch9aw9aw@github.com"

inputs:
  Superzaf:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"