name: "300117811 Cyrille"
description: "Hello Guys"
author: "300117811@monboreal.ca"

inputs:
  MY_NAME: 
    description: "Who to greet"
    required: true
    default: "Sio"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
