name: "Hello Actions"
description: "Hello guys"
author: "300119623@monboreal.ca"

inputs:
  MY_NAME: 
    description: "Hello"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
