name: "Hello Actions"
description: "Hello guys"
author: "Mariode@github.com"

inputs:
  MY_NAME:
    description: "Hello"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
