apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
    name: openelb-layer2-eip
    annotations:
      eip.openelb.kubesphere.io/is-default-eip: "true"
spec:
    address: 10.13.237.10-10.13.237.40
    protocol: layer2
    interface: enp2s0f0.  
    disable: false
status:
    occupied: false
    usage: 1
    poolSize: 10
    used: 
      "10.13.237.10": "default/test-svc" 
    firstIP: 10.13.237.10 
    lastIP: 10.13.237.40 
    ready: true
    v4: true
