#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp and docker.
groups:
  - ubuntu: [root,sys]
  - hashicorp
  - docker

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD2pLhMqFGKffSdYvNCMAyM7598oBY+m/3q5AMXmb7IE6vq42+yGzqEUzZu9WrFckFD4Hq52rIU5DeOvi83DCF3uroXjNTEtCKdi+tY7cV18bHmsDsBHMqTnpuvroofgFWA0Pi++b2kGW2I5eyy1Qjv5rOp7y11Xe6XeZFEz7qQO1/xNiBMJEruG9Xldgooe4hkaOF39qnbqD4ui3LxYaTUTEulstw4wN70dSB8Zu9YQP7A7KU2zIEwJ1aw8whfO1CAM/AVvoDyqMtV8VXoaZSHOBgluMtinQfyyt473S2ZZeJlnmhK0F1gdOhO4SVZNRMj96m30ryYkYBFWvvLRP5N b300098957@ramena
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNE581oWqb+edNzkoguUKNRdNbVxzSJrM0MFRiJ2MMOOzanamAXKunt5stD6UXw0rff1oDcj1M5f/S4noUcXBeBqiZiK9mpPGUhQmn52pP9o2MBYDLcIkezJmRrRnCMK2JPDo0we4Qs9U0os5VR8i/I6RUoPHVADFhLf4aPzm94LRgwIdJt/My49f/c91JAOK4i0oExNf5SBOttURdFY4Lir7bhPfz1ayo8NyzHTVyc7/j7lA69o+bO12HuYkXWkSMB9VQOTosZHiKKSUWJpXu9NP0vQmbO5tc5ULnUWhajpb9nivwJNe22YLUV8G767IEuhMa13wBjIb4u+Ad+/qkm+LxCCUH4n3lHdhVeRxwsroHtFuA3fWyHU6SAbVovTMXWhZvxiag1Y7kVB5PORB8MEnMn41UJKZIXWsh623JqOgjKjox8JDGcx73J7d6K11e7RVzaWmmzEnz4k6C8cHS965QvlMVaNS4mEd2Mz1JGl+mBDhxwsUqKygCJ1atISk= leona@Leonaldo

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - net-tools
  - jq

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1