apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-storage
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "maroc" # ME CHANGER VITE
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: " blockdevice-62204c92-e4ba-4693-8ba7-58a02c9392b5" # ME CHANGER VITE
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "mali"  # ME CHANGER VITE
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-3fa7d473-d0f1-4532-bcd4-a402241eeff1" # ME CHANGER VITE
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "bamako" # ME CHANGER VITE
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-7e848c90-cca2-4ef4-9fdc-90cff05d5bb5" # ME CHANGER VITE
     poolConfig:
       dataRaidGroupType: "stripe"
---
