apiVersion: openebs.io/v1alpha1
kind: BlockDevice
metadata:
  name: blockdevice-23e1292d-32f5-4528-8f7f-3abaee070a03
  labels:
    kubernetes.io/hostname: bellatrix
    ndm.io/managed: "false"
    ndm.io/blockdevice-type: blockdevice
status:
  claimState: Unclaimed
  state: Active
spec:
  capacity:
    logicalSectorSize: 512
    storage: 107374182400
  details:
    deviceType: lvm
  devlinks:
  - kind: by-id
    links:
    - /dev/disk/by-id/dm-uuid-LVM-3wU1GsK3RM9v8mInM2B300iKIJ9GlQssrdOs38ndKRjGqB4A4PKc893FS8heIdc3 
    - /dev/disk/by-id/dm-name-ubuntu--vg-iscsi--lv
  - kind: by-path
    links:
    - /dev/mapper/ubuntu--vg-iscsi--lv
  nodeAttributes:
    nodeName: bellatrix
  path: /dev/dm-1
