name: madmax 100028762
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./1.Docker/100028762
        with:
          MY_NAME: "madmax"
