name: Fes regne le monde
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./1.Docker/300124876
        with:
          MY_NAME: "Hafsa"
