name: action Pasmi
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./1.Docker/300120726
        with:
          MY_NAME: "hhhhh"
