name: 300124734 Mohamed
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./1.Docker/300124734
        with:
          MY_NAME: "Superzaf"
