name: 300119623
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./1.Docker/300119623
        with:
          MY_NAME: "mariode"
