name: 300127290
on: push
jobs:
  build:
    name: Bienvenu chez la grande dame
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./1.Docker/300127290
        with:
          MY_NAME: "sara"
